name: Swift Coverage Test

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches: [development, main]

jobs:
  cov:
    uses: cpslabgu/swift-workflows/.github/workflows/cov.yml@main
    secrets: inherit
